my_library/urls.py
from django.urls import path
from . import views


# set the 'app_name' to namespaceing in urls!!!
app_name = 'my_library'
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("books/", views.BookListView.as_view(), name="books"),
    path("book/<int:pk>/", views.BookDetailView.as_view(), name="book-detail"),
    path("authors/", views.AuthorListView.as_view(), name="authors"),
    path("author/<int:pk>/", views.AuthorDetailView.as_view(), name="author-detail"),
    path("mybooks/", views.LoanedBooksByUserModelListView.as_view(), name="my-borrowed"),
    path("book/<slug:pk>/renew/", views.renew_book_librarian, name="renew-book-librarian"),
    path("author/create/", views.AuthorCreateView.as_view(), name="author-create"),
    path("author/<int:pk>/update/", views.AuthorUpdateView.as_view(), name="author-update"),
    path("author/<int:pk>/delete/", views.AuthorDeleteView.as_view(), name="author-delete"),
]

polls/urls.py
from django.urls import path, re_path   # 're_path' is alias for 'url'
from . import views


# set the 'app_name' to namespaceing in urls!!!
app_name = 'polls'
urlpatterns = [
    path('', views.IndexListView.as_view(), name='index'),
    path("<int:pk>/", views.QuestionDetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultDetailView.as_view(), name="results"),
    # we should ues re_path for particular regex and for common ones should use <int:pk>, <str:pk> !!!
    # here is expample for re_path:
    # re_path(r"^(?P<pk>[0-9]+)/$", views.QuestionDetailView.as_view(), name="detail"),
    re_path(r"^(?P<question_id>[0-9]+)/vote/$", views.vote, name="vote"),
    



    # # or we can use re_path() to use regex and sending params in urls!!!!
    # re_path(r"^$", views.index, name="index"),
]

train1_django/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings              # these are for static and templates
from django.conf.urls.static import static    # these are for static and templates


urlpatterns = [
    path("mylibrary/", include('my_library.urls')),
    path("polls/", include('polls.urls')),
    path('admin/', admin.site.urls),
]

# this is for adding authentication ro site!!!
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path("accounts/",include('django.contrib.auth.urls')),
]



# # these are for static and templates
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_library/models.py
from django.db import models
import uuid  # Required for unique book instances
from django.urls import reverse
# Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User
# user with authenticating ability
from datetime import date


class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s, %s' % (self.last_name, self.first_name)

    # this is specific func for django that we override, return to specifc part on site.(maybe specific view)
    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('my_library:author-detail', args=[str(self.id)])


class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    # 'Book' as a string rather than object because it hasn't been declared yet in the file.
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Mainstance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved')
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              blank=True, default='m', help_text='Book availability')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL,
                                 null=True, blank=True)

    # the 'Meta' class is used for ordering the items of class in queries!
    # we set the fields that we want to sort based on in ordering list!!!
    class Meta:
        ordering = ["due_back"]
        # we can also set that null values were on the last!!!!
        permissions = [('can_renew_due_back', 'Can renew due back')]
        # set permission access!

    def __str__(self):
        """
        String for representing the Model object
        """
        return '%s (%s)' % (self.id, self.book.title)

    # property make it available same as filed :)
    # @property
    def _is_overdue(self):
        """
        if the due_back is over and been late return True
        else if have time return True
        """
        if self.due_back and (date.today() > self.due_back):
            return True
        return False
    # show icon instead of 'True' or 'False'
    _is_overdue.boolean = True
    _is_overdue.short_description = 'overdue for back?'
    _is_overdue.admin_order_field = 'due_back'
    # make property of func in other attribute
    is_overdue = property(_is_overdue)


class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000,
                               help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            help_text="13 Character <a href=https://www.isbn-international.org/content/what-isbn>ISBN number</a>")
    # as we can see here, we can ues html tags in help_text
    genre = models.ManyToManyField('Genre',
                                   help_text="Select a genre for this book")
    # ManyToManyField used because genre can contain many books. Books can cover many genres.

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    # this is specific func for django that we override, return to specifc part on site.(maybe specific view)
    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('my_library:book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        # query self.genre.all() and then access to name using genre.name for 3 of them!
        return ', '.join([genre.name for genre in self.genre.all()[:3]])
    # this is the title of column in list_display on admin panel!!!
    display_genre.short_description = 'Genre'


class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200,
                            help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

my_library/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime  # for checking renewal date range.


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text='Enter a date between now and 4 weeks (default 3).')

    def clean_renewal_date(self):
        date = self.cleaned_data["renewal_date"]

        # check date is not in past.
        if date < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check date is in range librarian allowed to change (+4 weeks).
        if date > (datetime.date.today() + datetime.timedelta(weeks=4)):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return date

my_library/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
# for reverse from 'class base' Views!
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import permission_required, login_required
# this for permission required for specific func View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
# for required login and required permission to specific View!
import datetime

from . import models
from . import forms


# def index(request):
#     """
#     View function for home page of site.
#     """
#     # Generate counts of some of the main objects
#     num_books = models.Book.objects.all().count()
#     num_instances = models.BookInstance.objects.all().count()
#     # Available books (status = 'a')
#     num_instances_available = models.BookInstance.objects.filter(status__exact='a'
#                                                                  ).count()
#     # The 'all()' is implied by default.
#     num_authors = models.Author.objects.all().count()
#
#     # Render the HTML template index.html with the data in the context variable
#     return render(request, 'my_library/index.html',
#                   context={'num_books': num_books, 'num_instances': num_instances,
#                            'num_instances_available': num_instances_available, 'num_authors': num_authors})
#
class IndexView(generic.TemplateView):
    template_name = "my_library/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["num_books"] = models.Book.objects.all().count()
        context["num_instances"] = models.BookInstance.objects.all().count()
        context["num_instances_available"] = models.BookInstance.objects.filter(
            status__exact='a').count()
        context["num_authors"] = models.Author.objects.all().count()
        return context


class BookListView(generic.ListView):
    model = models.Book
    template_name = "my_library/book_list.html"


class BookDetailView(generic.DetailView):
    model = models.Book
    template_name = "my_library/book_detail.html"


class AuthorListView(generic.ListView):
    model = models.Author
    template_name = "my_library/author_list.html"


class AuthorDetailView(generic.DetailView):
    model = models.Author
    template_name = "my_library/author_detail.html"


class LoanedBooksByUserModelListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing books on loan to current user. 
    """
    model = models.BookInstance
    template_name = "my_library/bookinstance_list_borrowed_user.html"
    paginate_by = 10
    # this for count of instances show on each page!

    def get_queryset(self):
        return models.BookInstance.objects.filter(borrower=self.request.user
                                                  ).filter(status__exact='o').order_by('due_back')


class AuthorCreateView(PermissionRequiredMixin, generic.CreateView):
    permission_required = ['my_library.add_author']
    # raise_exception = False
    model = models.Author
    # template_name = ".html"  ---> the default template view for create is "suffixname_form"
    fields = '__all__'
    initial = {'date_of_birth': '05/01/2018'}


class AuthorUpdateView(PermissionRequiredMixin, generic.UpdateView):
    permission_required = ['my_library.change_author']
    model = models.Author
    # template_name = ".html"  ---> the default template view for update is "suffixname_form"
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']


class AuthorDeleteView(PermissionRequiredMixin, generic.DeleteView):
    permission_required = ['my_library.delete_author']
    model = models.Author
    # template_name = ".html"  ---> the default template view for this delete "suffixname_confirm_delete"
    success_url = reverse_lazy('my_library:authors')
    # the success_url in others has default url, but in delete you should set it manually!


# # it didn't work, and don't let user access this View even if they the specific access!
@permission_required('my_library.can_renew_due_back')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    book_inst = get_object_or_404(models.BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':
        # Create a form instance and populate it with data from the request (binding):
        form = forms.RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('my_library:my-borrowed'))

    # If this is a GET (or any other method) create the default form.
    # when the user don't send post method (e.g. for first time loading page)
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = forms.RenewBookForm(
            initial={'renewal_date': proposed_renewal_date})

    return render(request, 'my_library/book_renew_librarian.html', {'form': form, 'bookinst': book_inst})

my_library/templates/my_library/author_confirm_delete.html
{% extends "my_library/base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
{% csrf_token %}
    <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

my_library/templates/my_library/author_detail.html
{% extends "my_library/base_generic.html" %}

{% block content %}

<h1>Author Information</h1>
<hr>
<h2>Author: {{ author.last_name }}</h2>
<h4><a href="{% url 'my_library:author-update' author.id %}">edit</a> | <a href="{% url 'my_library:author-delete' author.id %}">delete</a></h4>
<p><strong>author's first name:</strong> {{ author.first_name }}</p>
<p><strong>date of birth:</strong> {{ author.date_of_birth }}</p>
<p><strong>date of death:</strong> {{ author.date_of_death }}</p>
<hr>

<h3>Books</h3>
{% if author.book_set %}
<ul>

    {% for book in author.book_set.all %}
    <li>
        <h4><strong>Title:</strong> <a href="{{ book.get_absolute_url }}">{{ book.title }}</a></h4>
        <p>
            <strong>Genre:</strong>{% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %},{% endif %}{% endfor %}
            <br>
            <strong>Summary:</strong> {{ book.summary }}
        </p>
    </li>
    {% endfor %}
    
</ul>
{% else %}
<p>there are no books from this author yet.</p>
{% endif %}

{% endblock content %}

my_library/templates/my_library/author_form.html
{% extends "my_library/base_generic.html" %}

{% block content %}

<!-- in this place because it's with default forms we don't do anything in action -->
<form action="" method="post">
{% csrf_token %}
    
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>

{% endblock %}

my_library/templates/my_library/author_list.html
{% extends 'my_library/base_generic.html' %}

{% block content %}
<h1>Author List</h1>
{% for author in author_list %}
    <h2>Author:<a href="{{ author.get_absolute_url }}"> {{ author.last_name }}</a></h2>
    <h4><a href="{% url 'my_library:author-update' author.id %}">edit</a> | <a href="{% url 'my_library:author-delete' author.id %}">delete</a></h4>
    <p>author's first name: {{ author.first_name }}</p>
    <p>date of birth: {{ author.date_of_birth }}</p>
    <p>date of death: {{ author.date_of_death }}</p>
    <hr>
{% endfor %}

{% endblock content %}

my_library/templates/my_library/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>

    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'my_library/styles.css' %}">
</head>

<body>

    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'my_library:index' %}">Home</a></li>
                    <li><a href="{% url 'my_library:books' %}">All books</a></li>
                    <li><a href="{% url 'my_library:authors' %}">All authors</a></li>
                    <li><a href="/admin/">Admin Panel</a></li>
                    <li><a href="{% url 'my_library:my-borrowed' %}">My Borrowed</a></li>
                    <br>
                    {% if user.is_authenticated %}
                    <br>
                    <li>Authors Panel:</li>
                    <a href="{% url 'my_library:author-create' %}">new author</a><br>
                    <a href="{% url 'my_library:authors' %}">edit author</a><br>        <!-- link to authors to select one author and then edit or delete it -->
                    <a href="{% url 'my_library:authors' %}">delete author</a><br>      <!-- link to authors to select one author and then edit or delete it -->
                    <br>
                    <br>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li>User: {{ user.get_username }}</li>
                        <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
                    {% else %}
                        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
                    {% endif %} 
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}{% endblock %}
            </div>
        </div>

    </div>
</body>

</html>

my_library/templates/my_library/book_detail.html
{% extends "my_library/base_generic.html" %}

{% block content %}
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {{ book.language }}</p>
<p><strong>Genre:</strong>{% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %},{% endif %}{% endfor %}
</p>
strong>Summary:</strong> {{ book.summary }}
<div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
    </p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
</div>
{% endblock %}

my_library/templates/my_library/book_list.html
{% extends "my_library/base_generic.html" %}

{% block content %}
<h1>Book List</h1>

{% if book_list %}
<ul>

    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
    </li>
    {% endfor %}

</ul>
{% else %}
<p>There are no books in the library.</p>
{% endif %}

{% endblock %}

my_library/templates/my_library/book_renew_librarian.html
{% extends "my_library/base_generic.html" %}

{% block content %}

<h1>Renew: {{bookinst.book.title}}</h1>
<p>Borrower: {{bookinst.borrower}}</p>
<p{% if bookinst.is_overdue %} class="text-danger" {% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action=" {% url 'my_library:renew-book-librarian' bookinst.id %} " method="post">
    {% csrf_token %}
        <table>
            {{ form }}
        </table>

        <input type="submit" value="Submit" />
    </form>

{% endblock %}

my_library/templates/my_library/bookinstance_list_borrowed_user.html
{% extends "my_library/base_generic.html" %}

{% block content %}
<h1>Borrowed books</h1>

{% if bookinstance_list %}
<ul>

    {% for bookinst in bookinstance_list %}
    <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'my_library:book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>
         ({{ bookinst.due_back }}) -------------------------------- 
        {% if perms.my_library.can_renew_due_back %}
            <a href="{% url 'my_library:renew-book-librarian' bookinst.id %}">Renew due back</a>  
        {% endif %}
    </li>
    {% endfor %}

</ul>
{% else %}
<p>There are no books borrowed.</p>
{% endif %}

{% endblock %}

my_library/templates/my_library/index.html
{% extends "my_library/base_generic.html" %}

{% block content %}
<h1>Local Library Home</h1>

<p>Welcome to <em>LocalLibrary</em>, a very basic Django website </p>

<h2>Dynamic content</h2>

<p>The library has the following record counts:</p>
<ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
</ul>

{% endblock %}